openstates/task-definitions

- tasks/de.yml
This may address https://github.com/openstates/openstates/issues/2270.  It's a shot in the dark.
> Attempt to address DE scrape failures.

- tasks/pa.yml
Is this how we'd fix https://github.com/openstates/openstates/issues/2391 ?
> PA: fix oom

- tasks/la.yml
> LA: Begin scraping for 2019

- tasks/nm.yml
[Fixes https://github.com/openstates/openstates/issues/2780]
> NM: Re-enable votes.

- tasks/ia.yml
- tasks/mn.yml
IA's scraper was fixed in https://github.com/openstates/openstates/pull/3204, and MN's scraper was fixed in https://github.com/openstates/openstates/pull/3186.
> IA, MN: Enable vote scrapers

- tasks/tx.yml
Corresponds to https://github.com/openstates/openstates-scrapers/pull/3469
> TX: temporarily disable votes so we can get prefiles

- tasks/in.yml
- tasks/me.yml
- tasks/mt.yml
- tasks/nj.yml
- tasks/nv.yml
- tasks/ok.yml
- tasks/tn.yml
- tasks/tx.yml
- tasks/wa.yml
Also restore normal MT frequency as prefile bills has slowed the task considerably
> Increase scrape frequency for more early-session jurisdictions

- tasks/ia.yml
Not ready to merge yet, just queuing this one up for when IA bills start to appear in the normal location.
> IA: return to regular (not prefile) scraping

- tasks/ak.yml
- tasks/ar.yml
- tasks/de.yml
- tasks/il.yml
- tasks/ks.yml
- tasks/ky.yml
- tasks/me.yml
- tasks/mi.yml
- tasks/mn.yml
- tasks/nc.yml
- tasks/ok.yml
- tasks/or.yml
- tasks/pr.yml
- tasks/tn.yml
- tasks/va.yml
Only one I didn't touch is CA, which I assume is a special cause due to the SQL dumps, but if not could be more frequent
> Adjust frequences per freq analysis

- tasks/co.yml
- tasks/ga.yml
- tasks/ia.yml
- tasks/ks.yml
- tasks/mi.yml
- tasks/mn.yml
- tasks/mt.yml
- tasks/ri.yml
- tasks/wi.yml
- tasks/wv.yml
* A few states moved the schedule around, experimenting at getting missing bill time to a minimum level
* A few states adjusted based on the frequency recommendations script
> Missing bill time adjustments

- .gitignore
- tasks/al.yml
AL isn't in session at the moment, and the scraper keeps running into connection errors. Trying to alleviate since local scraper runs
> AL: drop frequency to avoid timeouts

- tasks/nh.yml
> fix cron syntax for nh

- environments.yml
> fix naming of access key

- environments.yml
> change environment variables to settings that work in other contexts

- environments.yml
Depends on https://github.com/openstates/openstates-core/pull/63
> add stats environment variables

- environments.yml
> correct endpoint for stats

- tasks/ak.yml
> add AK events

- tasks/va.yml
> add VA event scraping

- tasks/co.yml
> add CO event scraping

- tasks/mt.yml
> add event scraping for MT

- tasks/az.yml
> add event scraping for AZ

- tasks/ct.yml
> add CT event scraping

- tasks/fl.yml
> add event scraping for FL

- tasks/ia.yml
> add event scraping for IA

- tasks/wv.yml
> add WV event scraping

- tasks/ut.yml
> add UT event scraping

- tasks/or.yml
> add OR event scraping

- tasks/md.yml
> add event scraping to MD

- tasks/ny.yml
> add event scraping to NY

- tasks/us.yml
> add USA event scraping

- tasks/wa.yml
> add event scraping to WA

- tasks/al.yml
- tasks/ar.yml
- tasks/dc.yml
- tasks/de.yml
- tasks/ga.yml
- tasks/hi.yml
- tasks/id.yml
- tasks/il.yml
- tasks/in.yml
- tasks/ks.yml
> add half of missing event scrapers

- tasks/ca.yml
> enable CA events

- tasks/ne.yml
> increase frequency of NE scrape

- tasks/ok.yml
- tasks/tn.yml
I just noticed the list of jurisdictions we need realtime bills on are now 12 and not 10. I saw the updated list [here](https://civic-eagle.atlassian.net/browse/DATA-2276?focusedCommentId=17159) from @bfossen-ce 's comment.
> chore: add realtime flag to tn and ok

- tasks/ak.yml
- tasks/ar.yml
- tasks/az.yml
- tasks/co.yml
- tasks/ct.yml
- tasks/de.yml
- tasks/fl.yml
- tasks/hi.yml
- tasks/id.yml
- tasks/il.yml
- tasks/ky.yml
- tasks/ma.yml
- tasks/md.yml
- tasks/me.yml
- tasks/mi.yml
- tasks/ms.yml
- tasks/nd.yml
- tasks/oh.yml
- tasks/ok.yml
- tasks/pa.yml
- tasks/ri.yml
- tasks/sc.yml
- tasks/sd.yml
- tasks/tn.yml
- tasks/tx.yml
- tasks/ut.yml
- tasks/vt.yml
- tasks/wi.yml
- tasks/wv.yml
Trying to decrease the amount of time it takes to get a bill on OS collectively. Also changes the scrapers so they don't all run at the top of the hour too.
> Multi: increase bill scraper frequency

- tasks/ca.yml
- tasks/nd.yml
Depends on https://github.com/openstates/openstates-scrapers/pull/4449
Have CA scrapes execute the new entrypoint script
> CA task execution changes

- tasks/ak.yml
- tasks/ar.yml
- tasks/az.yml
- tasks/co.yml
- tasks/ga.yml
- tasks/hi.yml
- tasks/id.yml
- tasks/il.yml
- tasks/in.yml
- tasks/ks.yml
- tasks/ky.yml
- tasks/md.yml
- tasks/mn.yml
- tasks/mo.yml
- tasks/ms.yml
- tasks/mt.yml
- tasks/nm.yml
- tasks/sc.yml
- tasks/sd.yml
- tasks/tn.yml
- tasks/ut.yml
- tasks/va.yml
- tasks/vt.yml
- tasks/wa.yml
- tasks/wv.yml
- tasks/wy.yml
This PR lowers the cron job frequency for 26 jurisdictions and adjusts the time of several jobs to create 5 or 10 minute incremental gaps between start times of jobs that would otherwise be occurring around the common times of 6am and 7am.
> May2023 decrease freq

- tasks/us.yml
> US: add votes to scrape

- tasks/ca.yml
Existing events scraper based on bulk SQL files finds very few events that are in the future. Any concerns just swapping it out?
Here's a look at 2024 legislative events in the DB currently (as delivered by the existing events scraper):
```
+----------------------------------------------+-------------------------+------------------------------------------------------------------------------------+
|id                                            |start_date               |name                                                                                |
+----------------------------------------------+-------------------------+------------------------------------------------------------------------------------+
|ocd-event/1916761a-046f-4850-af75-2c04fe4734bc|2024-01-04T08:00:00+00:00|Commi …
```
> CA: use new website-targeting scraper for events

- tasks/de.yml
Airflow is struggling to get through a run, just want to see if it works here
> DE: add task back
